### PR TITLE
[ENG-4366] Fix payload user patch

### PR DESCRIPTION
**Pull request by lukeasrodgers**
Need to pass these along to actually update user permissions. needs specs

### CODE REVIEW

**Comment by camkidman** [comment]
Deployed [this branch](https://github.com/alice-financial/alice/compare/ENG-4366-test-close-user-call) to staging, but it didn't seem to update the user. I made a few different calls on a couple different users with the synapse_system_ids 5d49daccd83c198065c2e81a, 5d10eb16623ff969b971c101 (testing with a couple different current `permission` statuses to see if a user had to be in a certain permission to update to closed).

I think in our chat you mentioned the code in this PR seemed to work for a user, is there something different you may have done @lukeasrodgers or is that just the nature of Synapse's UAT environment?

**Comment by lukeasrodgers** [comment]
thanks for testing that @camkidman - looks like i was mis-remembering the payload structure, i just tested locally and seems like those keys _cannot_ be nested in the `update` hash. I fixed and tried this locally and it seemed to work.

**Comment by camkidman** [comment]
💥 
```ruby
syn = Banking::SynapseUser.find_by(synapse_system_id: "5d10eb16623ff969b971c101")
Banking::BankingSystemService.deactivate_user!(syn)
```

image

**Review by camkidman — APPROVED** [review]
I think this makes sense to ship if you're comfortable with it. The parameters only get added to the call if they're present and it should only get called in the [`close_user`](https://github.com/alice-financial/alice/blob/develop/lib/third_party_interfaces/banking/synapse/synapse_interface.rb#L347-L356) call which I verified functions with these additions

**Comment by camkidman** [comment]
BTW you may have already known this but I found out you can debug the requests of anything using RestClient by dropping `RestClient.log = "stdout"` into a console and it'll output the requests 🎉

**Comment by lukeasrodgers** [comment]
sgtm - yeah the restclient thing is cool, we've considered using it to log request body to redis (or even s3) to help with debugging, but never actually implemented it (partly cuz it could have non-trivial performance implications if not done carefully)

**Pull request merged**
